# Site settings
language:               ""
title:                  "includeOS"
description:            "IncludeOS is an open source library operating system."
# google-verification:    ""

# Handling Reading
include:
  - ".htaccess"
  - "_pages"

exclude:
  - "/assets/"
  - "bower.json"
  - "composer.json"
  - "composer.lock"
  - "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "/gulp/"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"

# Plugins
plugins:             ["jekyll-sitemap", "jekyll-paginate"]

# Conversion
incremental:      true

# Serving
# url:            ""
# baseurl:        "" # does not include hostname

# Outputting
permalink:        "/blog/:year/:title.html"
paginate_path:    "/blog/page:num"
paginate:         5

compress_html:
  ignore:
    envs: [development]

source:      _src
destination: _dest
